# Generated by Django 2.2.3 on 2020-01-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='champ',
        ),
        migrations.AddField(
            model_name='profile',
            name='champion',
            field=models.CharField(default='test', max_length=3),
        ),
    ]
