# Generated by Django 2.2.3 on 2020-01-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200102_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='champion',
            field=models.CharField(choices=[('GER', 'Deutschland'), ('ESP', 'Spanien'), ('ENG', 'England')], default='spanien', max_length=12),
        ),
    ]
