# Generated by Django 2.2.3 on 2020-01-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200104_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_joker',
            field=models.IntegerField(default=0),
        ),
    ]
