# Generated by Django 2.0.4 on 2020-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_champion',
            field=models.CharField(choices=[('ger', 'deutschland'), ('spa', 'spanien'), ('eng', 'England'), ('fra', 'Frankreich'), ('ITA', 'Italien'), ['----', '----']], default='----', max_length=12),
        ),
    ]
