# Generated by Django 2.0.4 on 2020-03-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion',
            old_name='out',
            new_name='eliminated',
        ),
        migrations.AlterField(
            model_name='champion',
            name='champion',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Tip.Team'),
        ),
    ]
