# Generated by Django 2.2.3 on 2020-01-31 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='champion',
            field=models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='champion', to='Tip.Team'),
        ),
    ]
