# Generated by Django 2.0.4 on 2019-10-04 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0002_auto_20191004_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='team_rank',
            field=models.IntegerField(default=1),
        ),
    ]
