# Generated by Django 2.2.3 on 2020-01-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0003_auto_20200131_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='not_eliminated',
        ),
        migrations.AddField(
            model_name='champion',
            name='eliminated',
            field=models.BooleanField(default=0),
        ),
    ]
