# Generated by Django 2.0.4 on 2019-10-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0003_auto_20191004_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tip.Match'),
        ),
    ]
