# Generated by Django 2.2.3 on 2020-01-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0005_auto_20200102_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
