# Generated by Django 2.2.3 on 2020-01-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0006_auto_20200102_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_time',
            new_name='match_date',
        ),
        migrations.AddField(
            model_name='match',
            name='guest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
    ]
