# Generated by Django 2.2.3 on 2020-01-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0008_auto_20200104_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='tip',
        ),
    ]
