# Generated by Django 2.2.3 on 2020-01-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0010_auto_20200107_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_type',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='matchday',
        ),
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(default=0),
        ),
    ]
