# Generated by Django 2.2.3 on 2020-01-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0011_auto_20200107_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='date_posted',
            new_name='tip_date',
        ),
    ]
