# Generated by Django 2.2.3 on 2020-01-13 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0012_auto_20200108_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='joker',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='guest_team',
            field=models.ForeignKey(default='tba', on_delete=django.db.models.deletion.CASCADE, related_name='guest_team', to='Tip.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(default='tba', on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='Tip.Team'),
        ),
    ]
