# Generated by Django 2.2.3 on 2020-01-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0013_auto_20200113_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='champion',
            field=models.CharField(max_length=100),
        ),
    ]
